apiVersion: apps/v1
kind: Deployment
metadata:
  name: jinyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jinyer
  template:
    metadata:
      labels:
        app: jinyer
    spec:
      containers:
      - image: okteto.dev/ray:jinyer
        name: jinyer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "587a9712-6b79-4049-86c8-353d0793ce9f"
        - name: Vless_Path
          value: "/ray"
        - name: Vmess_UUID
          value: "587a9712-6b79-4049-86c8-353d0793ce9f"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
